# Documentation for GitLab CI is here: https://docs.gitlab.com/ee/topics/build_your_application.html
stages:
    - build
    - test

build:
    stage: build
    # TODO: This job should build a container image for demo_app that
    # can be used in the `test` stage later.

test:
    stage: test
    image: quay.io/curl/curl-base:latest
    variables:
        POSTGRES_DB: custom_db
        POSTGRES_USER: custom_user
        POSTGRES_PASSWORD: custom_pass
        FF_NETWORK_PER_BUILD: 1
        GRAPHQL_URL: http://demo_app/graphql

    services:
        - postgres
        - name: "" # TODO: Use the image built in the `build` stage.
          alias: "demo_app"
          variables:
              DJANGO_CONFIGURATION: Development
    script: # this assumes the fixture data has been loaded into the database
        - apk add jq
        - ./run_graphql_tests.sh
