# Generated by Django 3.2.16 on 2023-10-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_level', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'grade_levels',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_using_scheduling', models.BooleanField()),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('difficulty', models.FloatField()),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schooldata.gradelevel')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
